In [ ]:
# if you are using Jupyter notebook execute 1st:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
# Dense: to add layers(hidden, output)
from tensorflow.keras import Sequential
# Sequential: to add layers in sequence, to initialize ann model i.e. initially random weight will be assigned
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df # Exited is a target column. Binary Classification problem
# given the customer details, bank want to predict whether customer will leave the bank or not.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Not important columns
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

# Data Transformation

In [ ]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.drop(columns = ['Exited']) # no permanent deletion of Exited column

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [ ]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype = int)  # dtype = int to make encoded values (0,1) permanent
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

# Model Building

In [ ]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [ ]:
sc = StandardScaler() # don't perform standardization on target column
x = df.drop(columns=['Exited'])# exclude Exited column
y = df['Exited']

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [ ]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
# create instance of Sequential class or initialize the model
model = Sequential()
# Sequential is a class in Keras that allows you to build ANN model layer-by-layer.
# create neurons in input, hidden and output layers and assign random weights to input
# In I/P layer 13 input values will be there as there are 13 independent features

#Add hidden layer, randomly 10 neurons are added
model.add(Dense(units=10,activation='relu'))# as target is binary use relu activation
# Layers are added sequentially using the .add() method.
# Each layer receives input from the previous layer and passes output to the next one.

#Add output layer
model.add(Dense(units=1, activation='sigmoid'))# for binary classification use sigmoid activation in output layer

#Establish the connection between the layers
model.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])
# adadelta is gradient descent algorithm for weight updation which we have selected randomly. We will hypertune it afterwards
# binary_crossentropy: also called log_loss, finds erros, range is 0 to 1

#Fit the data, perform forward and back propagation
model.fit(xtrain,ytrain, epochs=100)
# epochs=100 means that the model will go through the entire xtrain and ytrain dataset 100 times during training.
# epoch: backward and forward propagation will be done for 100 times
# The number of batches per epoch = Total number of samples / Batch size (default is 32)
# 80% training data = 8000 samples. So Batches=8000/32 = 250
# Each batch is processed in sequence during each epoch,
# and after all 250 batches are processed, one epoch is complete.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4663 - loss: 0.9323
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4802 - loss: 0.9318
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4749 - loss: 0.9244
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4812 - loss: 0.9161
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4766 - loss: 0.9229
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4810 - loss: 0.9287
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4869 - loss: 0.9043
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4839 - loss: 0.9073
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4761 - loss: 0.9169
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4851 - loss: 0.9030
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.4852 - loss: 0.8954
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.4758 - loss: 0.9171
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.4887 - loss: 0.9031
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4867 - loss: 0.9032
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4898 - loss: 0.9009
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4876 - loss: 0.9038
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4899 - loss: 0.8997
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4963 - loss: 0.8844
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4889 - loss: 0.8944
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5014 - loss: 0.8821
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4948 - loss: 0.8850
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4956 - loss: 0.8922
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4988 - loss: 0.8896
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4943 - loss: 0.8897
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5050 - loss: 0.8728
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4991 - loss: 0.8877
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5032 - loss: 0.8735
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5040 - loss: 0.8748
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5066 - loss: 0.8781
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5140 - loss: 0.8619
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5128 - loss: 0.8679
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5019 - loss: 0.8778
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5066 - loss: 0.8684
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5077 - loss: 0.8701
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5191 - loss: 0.8640
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5149 - loss: 0.8600
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5153 - loss: 0.8538
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5084 - loss: 0.8633
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5141 - loss: 0.8594
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5288 - loss: 0.8570
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5175 - loss: 0.8547
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5142 - loss: 0.8566
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5251 - loss: 0.8373
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5219 - loss: 0.8523
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5273 - loss: 0.8394
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5232 - loss: 0.8451
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5229 - loss: 0.8449
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5280 - loss: 0.8317
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5303 - loss: 0.8468
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5300 - loss: 0.8331
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5284 - loss: 0.8347
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5284 - loss: 0.8319
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5349 - loss: 0.8319
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5261 - loss: 0.8393
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5350 - loss: 0.8256
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5336 - loss: 0.8295
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5384 - loss: 0.8196
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5280 - loss: 0.8338
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5375 - loss: 0.8268
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5393 - loss: 0.8162
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5347 - loss: 0.8213
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5417 - loss: 0.8194
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5434 - loss: 0.8076
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5299 - loss: 0.8235
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5428 - loss: 0.8081
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5425 - loss: 0.8130
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5354 - loss: 0.8222
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5459 - loss: 0.8123
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5354 - loss: 0.8124
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5454 - loss: 0.8056
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5500 - loss: 0.8079
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5503 - loss: 0.7993
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5476 - loss: 0.8010
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5545 - loss: 0.7960
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5567 - loss: 0.7943
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5409 - loss: 0.8107
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5443 - loss: 0.8086
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5570 - loss: 0.7913
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5563 - loss: 0.7882
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5529 - loss: 0.7869
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5502 - loss: 0.7956
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5484 - loss: 0.7921
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5496 - loss: 0.7967
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5579 - loss: 0.7817
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5456 - loss: 0.7946
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5594 - loss: 0.7836
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5593 - loss: 0.7869
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5496 - loss: 0.7919
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5615 - loss: 0.7839
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5653 - loss: 0.7767
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5668 - loss: 0.7753
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5573 - loss: 0.7732
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5624 - loss: 0.7688
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5579 - loss: 0.7783
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5606 - loss: 0.7716
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5521 - loss: 0.7876
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5696 - loss: 0.7700
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5716 - loss: 0.7665
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5611 - loss: 0.7704
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5646 - loss: 0.7703

In [ ]:
# accuracy is not good and error is also high as hyperparameter tuning is not done
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
ypred = model.predict(xtest)
ypred # in dataset target column values are 0 or 1, but here output is a continuous number
# because in output layer activation function is sigmoid. It gives you o/p in terms of probability
# In sigmoid if probability is > 0.5 it gives you 1 and if probability < 0 it should give 0

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.42869538],
       [0.528815  ],
       [0.26797554],
       ...,
       [0.78595513],
       [0.40966946],
       [0.4918189 ]], dtype=float32)

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
ypred > 0.5 # not it will give me 1 or 0 OR true or false answers

array([[False],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [ ]:
ypred = ypred > 0.5
ypred

array([[False],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.83      0.59      0.69      1585
           1       0.26      0.54      0.35       415

    accuracy                           0.58      2000
   macro avg       0.54      0.57      0.52      2000
weighted avg       0.71      0.58      0.62      2000

# Hyperparameter Tuning

In [ ]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras->keras-tuner) (4.14.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 9.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

# **Tuning the ANN Model**
- Selecting the best optimizer

In [ ]:
import keras_tuner as kt

In [ ]:
# tuning for optimizer(adam,rmsprop or sgd:stochastic gradient descent) only
def optimizer_selection(hp):
    # hp (HyperParameters) is an object used to define search spaces for the hyperparameters you want to tune.
    # This allows the Keras Tuner to explore different values for the hyperparameters
    # and find the best ones during the search.

    #create instance of sequential class
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop']) #value of optimizer is categorical so use choice()function else use hp.Int()
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [ ]:
# similar to GridSearchCV() we will use here RandomSearch()
tuner = kt.RandomSearch(
    optimizer_selection,# model name-here Sequential() class is our model
    objective='val_accuracy', # increase accuracy of test data i.e. validation test accuracy or minimize 'val_loss'
    max_trials=3 # for each optimizer take 3 trials: for sgd-3 trials, for adam-3 trials, for rmsprop-3 trials
    # can select 3 to 10 or 20 for larger problems
)

In [ ]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))
# tuner.search() is equivalent to grid.fit()
# When we call tuner.search(), we are not directly calling the hyper() function.
# Instead, Keras Tuner automatically calls hyper()
# and passes the hp object to it during the search.
# We don’t manually pass hp as an argument because Keras Tuner handles it behind the scenes.

# epochs should be same as max_trials so 3 is selected
# validation_data: pass test data

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8084999918937683

Best val_accuracy So Far: 0.8144999742507935
Total elapsed time: 00h 00m 16s

In [ ]:
tuner.get_best_hyperparameters()[0].values # as per performance all optimizers are stored in an array
# we want high accuracy optimizer present at index 0 location

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0] # get best model: rmsprop
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8185 - loss: 0.4197 - val_accuracy: 0.8200 - val_loss: 0.4183
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8265 - loss: 0.4067 - val_accuracy: 0.8285 - val_loss: 0.4018
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8415 - loss: 0.3824 - val_accuracy: 0.8375 - val_loss: 0.3887
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8447 - loss: 0.3824 - val_accuracy: 0.8445 - val_loss: 0.3773
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8425 - loss: 0.3824 - val_accuracy: 0.8530 - val_loss: 0.3700
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8462 - loss: 0.3682 - val_accuracy: 0.8535 - val_loss: 0.3618
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8516 - loss: 0.3641 - val_accuracy: 0.8555 - val_loss: 0.3581
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8437 - loss: 0.3715 - val_accuracy: 0.8565 - val_loss: 0.3572
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8533 - loss: 0.3554 - val_accuracy: 0.8575 - val_loss: 0.3522
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8544 - loss: 0.3565 - val_accuracy: 0.8565 - val_loss: 0.3484
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8574 - loss: 0.3500 - val_accuracy: 0.8595 - val_loss: 0.3466
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8618 - loss: 0.3382 - val_accuracy: 0.8615 - val_loss: 0.3470
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8477 - loss: 0.3605 - val_accuracy: 0.8625 - val_loss: 0.3461
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8563 - loss: 0.3449 - val_accuracy: 0.8590 - val_loss: 0.3449
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3364 - val_accuracy: 0.8625 - val_loss: 0.3439
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8607 - loss: 0.3413 - val_accuracy: 0.8620 - val_loss: 0.3436
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8562 - loss: 0.3443 - val_accuracy: 0.8615 - val_loss: 0.3430
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8569 - loss: 0.3457 - val_accuracy: 0.8630 - val_loss: 0.3434
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8594 - loss: 0.3433 - val_accuracy: 0.8625 - val_loss: 0.3425
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8607 - loss: 0.3383 - val_accuracy: 0.8595 - val_loss: 0.3413
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8595 - loss: 0.3447 - val_accuracy: 0.8600 - val_loss: 0.3411
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8603 - loss: 0.3400 - val_accuracy: 0.8600 - val_loss: 0.3420
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8600 - loss: 0.3428 - val_accuracy: 0.8600 - val_loss: 0.3413
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3336 - val_accuracy: 0.8590 - val_loss: 0.3396
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8613 - loss: 0.3431 - val_accuracy: 0.8625 - val_loss: 0.3404
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8671 - loss: 0.3311 - val_accuracy: 0.8590 - val_loss: 0.3391
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8614 - loss: 0.3332 - val_accuracy: 0.8590 - val_loss: 0.3397
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8607 - loss: 0.3394 - val_accuracy: 0.8585 - val_loss: 0.3399
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3319 - val_accuracy: 0.8650 - val_loss: 0.3395
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8633 - loss: 0.3364 - val_accuracy: 0.8620 - val_loss: 0.3406
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3372 - val_accuracy: 0.8610 - val_loss: 0.3404
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8603 - loss: 0.3336 - val_accuracy: 0.8635 - val_loss: 0.3399
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8641 - loss: 0.3343 - val_accuracy: 0.8625 - val_loss: 0.3393
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8617 - loss: 0.3438 - val_accuracy: 0.8620 - val_loss: 0.3392
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8649 - loss: 0.3294 - val_accuracy: 0.8620 - val_loss: 0.3386
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8648 - loss: 0.3432 - val_accuracy: 0.8625 - val_loss: 0.3379
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8632 - loss: 0.3379 - val_accuracy: 0.8635 - val_loss: 0.3389
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8617 - loss: 0.3397 - val_accuracy: 0.8595 - val_loss: 0.3390
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8634 - loss: 0.3363 - val_accuracy: 0.8640 - val_loss: 0.3381
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8608 - loss: 0.3430 - val_accuracy: 0.8605 - val_loss: 0.3386
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8602 - loss: 0.3372 - val_accuracy: 0.8650 - val_loss: 0.3402
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8586 - loss: 0.3460 - val_accuracy: 0.8640 - val_loss: 0.3387
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8678 - loss: 0.3292 - val_accuracy: 0.8630 - val_loss: 0.3391
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8619 - loss: 0.3422 - val_accuracy: 0.8635 - val_loss: 0.3388
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8629 - loss: 0.3345 - val_accuracy: 0.8650 - val_loss: 0.3385
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3369 - val_accuracy: 0.8650 - val_loss: 0.3381
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8620 - loss: 0.3386 - val_accuracy: 0.8610 - val_loss: 0.3380
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8663 - loss: 0.3307 - val_accuracy: 0.8635 - val_loss: 0.3390
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8618 - loss: 0.3311 - val_accuracy: 0.8625 - val_loss: 0.3377
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3410 - val_accuracy: 0.8635 - val_loss: 0.3373
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8697 - loss: 0.3317 - val_accuracy: 0.8635 - val_loss: 0.3374
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8716 - loss: 0.3219 - val_accuracy: 0.8625 - val_loss: 0.3383
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8569 - loss: 0.3478 - val_accuracy: 0.8640 - val_loss: 0.3379
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8608 - loss: 0.3417 - val_accuracy: 0.8640 - val_loss: 0.3383
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8736 - loss: 0.3216 - val_accuracy: 0.8640 - val_loss: 0.3379
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3416 - val_accuracy: 0.8640 - val_loss: 0.3397
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8555 - loss: 0.3512 - val_accuracy: 0.8650 - val_loss: 0.3378
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8645 - loss: 0.3366 - val_accuracy: 0.8645 - val_loss: 0.3380
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8685 - loss: 0.3302 - val_accuracy: 0.8655 - val_loss: 0.3386
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8700 - loss: 0.3336 - val_accuracy: 0.8665 - val_loss: 0.3391
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8648 - loss: 0.3337 - val_accuracy: 0.8680 - val_loss: 0.3392
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8637 - loss: 0.3396 - val_accuracy: 0.8620 - val_loss: 0.3372
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8676 - loss: 0.3320 - val_accuracy: 0.8635 - val_loss: 0.3377
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8654 - loss: 0.3375 - val_accuracy: 0.8635 - val_loss: 0.3367
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3416 - val_accuracy: 0.8615 - val_loss: 0.3383
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8652 - loss: 0.3295 - val_accuracy: 0.8620 - val_loss: 0.3378
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8689 - loss: 0.3253 - val_accuracy: 0.8650 - val_loss: 0.3369
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8657 - loss: 0.3326 - val_accuracy: 0.8645 - val_loss: 0.3382
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8639 - loss: 0.3380 - val_accuracy: 0.8620 - val_loss: 0.3371
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8642 - loss: 0.3378 - val_accuracy: 0.8660 - val_loss: 0.3377
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8664 - loss: 0.3305 - val_accuracy: 0.8655 - val_loss: 0.3383
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8661 - loss: 0.3296 - val_accuracy: 0.8625 - val_loss: 0.3364
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8639 - loss: 0.3397 - val_accuracy: 0.8630 - val_loss: 0.3368
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8673 - loss: 0.3258 - val_accuracy: 0.8635 - val_loss: 0.3381
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8594 - loss: 0.3365 - val_accuracy: 0.8625 - val_loss: 0.3382
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8580 - loss: 0.3458 - val_accuracy: 0.8610 - val_loss: 0.3378
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8613 - loss: 0.3401 - val_accuracy: 0.8645 - val_loss: 0.3371
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8660 - loss: 0.3314 - val_accuracy: 0.8635 - val_loss: 0.3373
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8581 - loss: 0.3475 - val_accuracy: 0.8620 - val_loss: 0.3364
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3351 - val_accuracy: 0.8630 - val_loss: 0.3370
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8653 - loss: 0.3281 - val_accuracy: 0.8645 - val_loss: 0.3384
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8645 - loss: 0.3321 - val_accuracy: 0.8635 - val_loss: 0.3373
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8588 - loss: 0.3448 - val_accuracy: 0.8635 - val_loss: 0.3362
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8576 - loss: 0.3490 - val_accuracy: 0.8640 - val_loss: 0.3392
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8643 - loss: 0.3303 - val_accuracy: 0.8670 - val_loss: 0.3387
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3398 - val_accuracy: 0.8655 - val_loss: 0.3379
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3343 - val_accuracy: 0.8650 - val_loss: 0.3367
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8669 - loss: 0.3338 - val_accuracy: 0.8615 - val_loss: 0.3362
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8673 - loss: 0.3304 - val_accuracy: 0.8665 - val_loss: 0.3374
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8640 - loss: 0.3357 - val_accuracy: 0.8670 - val_loss: 0.3371
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8584 - loss: 0.3446 - val_accuracy: 0.8655 - val_loss: 0.3373
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3295 - val_accuracy: 0.8685 - val_loss: 0.3392
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3248 - val_accuracy: 0.8640 - val_loss: 0.3368
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8614 - loss: 0.3388 - val_accuracy: 0.8670 - val_loss: 0.3377
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8663 - loss: 0.3361 - val_accuracy: 0.8645 - val_loss: 0.3360
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3389 - val_accuracy: 0.8655 - val_loss: 0.3374
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8649 - loss: 0.3313 - val_accuracy: 0.8660 - val_loss: 0.3364
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8665 - loss: 0.3300 - val_accuracy: 0.8690 - val_loss: 0.3371
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8663 - loss: 0.3324 - val_accuracy: 0.8645 - val_loss: 0.3360
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8693 - loss: 0.3227 - val_accuracy: 0.8690 - val_loss: 0.3371

In [ ]:
# In above output we have only hypertuned optimizer and
# we got generalized model having improved accuracy- previously it was 76%
# now we got training accuracy=86.47% and testing accuracy=86.40%
model.evaluate(xtrain,ytrain) # same as score() function

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3344

[0.33285218477249146, 0.8628749847412109]

In [ ]:
model.evaluate(xtest,ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8703 - loss: 0.3458

[0.33710649609565735, 0.8690000176429749]

# Regression

In [ ]:
df = pd.read_csv('/content/Price.csv')
df

          price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [ ]:
x = df.iloc[:,1:]
y = df['price']

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [ ]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))# hidden layer1
ann.add(Dense(units=20, activation='relu'))# hidden layer2

ann.add(Dense(units=1))# output layer.
#In Regression task no activation function is required in output layer as we don't have to convert price to 0 or 1

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 257312.7812 - val_loss: 262794.2500
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 248155.8125 - val_loss: 262247.1250
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 262624.0000 - val_loss: 261423.5781
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 249103.8750 - val_loss: 260099.6406
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 250332.4844 - val_loss: 257942.9062
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 248272.6406 - val_loss: 254638.5781
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 245418.9531 - val_loss: 249784.3125
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 239435.8125 - val_loss: 243077.2188
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 236418.3438 - val_loss: 234220.5000
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 226559.8594 - val_loss: 223209.8750
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 210380.9531 - val_loss: 209950.3125
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 201611.7969 - val_loss: 194430.4219
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 183986.7188 - val_loss: 177152.0469
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 164026.3281 - val_loss: 158487.6562
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 143998.4375 - val_loss: 138968.0469
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 127980.5469 - val_loss: 118968.8516
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 106528.7109 - val_loss: 99411.8438
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 86516.2344 - val_loss: 80946.5547
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 68711.4766 - val_loss: 64266.5352
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 53392.4258 - val_loss: 49592.3555
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 40836.7617 - val_loss: 37501.9531
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31972.0449 - val_loss: 27738.3594
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23146.0312 - val_loss: 20546.9902
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 16960.4395 - val_loss: 15356.5938
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 13228.0234 - val_loss: 11811.8252
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9636.3457 - val_loss: 9442.2295
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8222.6260 - val_loss: 7894.2544
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7120.7822 - val_loss: 6867.9292
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6369.7710 - val_loss: 6182.1011
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5711.7446 - val_loss: 5673.0195
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5226.8672 - val_loss: 5287.9248
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5032.8833 - val_loss: 4962.2529
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4870.3452 - val_loss: 4698.3398
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4792.0195 - val_loss: 4439.8545
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4715.3794 - val_loss: 4204.7876
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4014.7556 - val_loss: 3970.6538
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4049.8054 - val_loss: 3766.7676
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4071.3223 - val_loss: 3561.1978
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3877.5710 - val_loss: 3362.3643
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3215.7168 - val_loss: 3183.0476
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3230.8679 - val_loss: 3009.7019
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2901.8452 - val_loss: 2843.7358
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2605.1572 - val_loss: 2686.6887
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2762.6687 - val_loss: 2533.5645
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2601.3247 - val_loss: 2386.2007
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2386.2771 - val_loss: 2249.2432
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2317.2876 - val_loss: 2117.0615
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2100.8567 - val_loss: 1995.4613
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2139.1436 - val_loss: 1876.4624
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1998.2257 - val_loss: 1769.8007
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1913.5446 - val_loss: 1662.1501
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1621.9863 - val_loss: 1569.2517
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1776.2405 - val_loss: 1473.0211
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1466.6044 - val_loss: 1395.7653
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1677.4391 - val_loss: 1310.0963
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1366.1600 - val_loss: 1235.4513
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1244.6334 - val_loss: 1164.8832
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1143.1804 - val_loss: 1102.3501
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1083.1215 - val_loss: 1040.8523
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1161.3325 - val_loss: 980.8605
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1178.2488 - val_loss: 928.3244
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 944.5044 - val_loss: 876.9858
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 776.8900 - val_loss: 829.6012
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 975.6408 - val_loss: 785.6443
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 794.9662 - val_loss: 740.2570
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 730.2172 - val_loss: 707.4225
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 645.5971 - val_loss: 674.9208
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 740.0191 - val_loss: 635.0070
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 570.0891 - val_loss: 604.4171
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 473.3707 - val_loss: 577.7708
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 525.8353 - val_loss: 549.5118
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 436.1267 - val_loss: 524.7090
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 423.1569 - val_loss: 500.4727
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 517.1448 - val_loss: 478.7989
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 422.1183 - val_loss: 457.2429
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 500.8437 - val_loss: 437.8754
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 418.5527 - val_loss: 417.6954
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 402.0481 - val_loss: 401.6752
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 373.7204 - val_loss: 386.0013
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 344.2523 - val_loss: 368.4520
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 300.0658 - val_loss: 356.6800
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 343.5002 - val_loss: 343.4496
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 381.7109 - val_loss: 329.8455
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 339.9291 - val_loss: 316.4385
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 255.4655 - val_loss: 306.7404
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 310.8591 - val_loss: 295.4958
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 227.7208 - val_loss: 286.7016
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 257.7497 - val_loss: 275.7455
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 263.9131 - val_loss: 265.6714
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 214.2494 - val_loss: 259.1382
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 249.5247 - val_loss: 249.7273
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 206.1600 - val_loss: 242.2138
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 250.0171 - val_loss: 236.0720
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 208.1485 - val_loss: 226.6503
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 190.0738 - val_loss: 220.5251
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 187.3430 - val_loss: 215.4014
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 168.6818 - val_loss: 208.2640
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 180.6339 - val_loss: 201.6005
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 203.4101 - val_loss: 196.7296
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 145.0324 - val_loss: 191.6275

In [ ]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

array([[482.94647],
       [525.708  ],
       [499.5794 ],
       [537.80994],
       [648.96686],
       [329.18076],
       [342.93512],
       [371.63232],
       [709.2999 ],
       [507.86322],
       [484.14624],
       [508.89066],
       [499.6322 ],
       [363.85498],
       [546.4917 ],
       [498.44974],
       [573.42786],
       [547.73663],
       [487.3851 ],
       [502.17972],
       [476.84308],
       [604.85254],
       [446.62558],
       [578.2863 ],
       [429.6054 ],
       [522.39954],
       [386.60468],
       [506.7776 ],
       [542.0313 ],
       [344.47427],
       [448.1019 ],
       [641.13446],
       [558.7554 ],
       [538.48486],
       [602.7193 ],
       [551.46277],
       [413.82898],
       [570.0491 ],
       [565.42035],
       [524.2789 ],
       [425.3569 ],
       [720.82074],
       [524.9166 ],
       [531.1849 ],
       [519.9518 ],
       [456.06226],
       [529.469  ],
       [529.9442 ],
       [583.7267 ],
       [470.92703],
       [388.62814],
       [622.44965],
       [797.7649 ],
       [531.94006],
       [654.2274 ],
       [544.23566],
       [492.9237 ],
       [542.87396],
       [548.3388 ],
       [368.3016 ],
       [644.60284],
       [474.8245 ],
       [485.76736],
       [507.82266],
       [559.70966],
       [333.52618],
       [552.8992 ],
       [546.27057],
       [445.71075],
       [595.418  ],
       [561.5433 ],
       [430.68112],
       [463.95108],
       [664.6654 ],
       [398.8654 ],
       [550.1209 ],
       [325.90945],
       [453.71887],
       [600.91016],
       [540.4472 ],
       [445.56824],
       [446.99988],
       [354.0011 ],
       [462.4263 ],
       [399.04932],
       [656.223  ],
       [389.77713],
       [553.9804 ],
       [565.9939 ],
       [362.22025],
       [413.51016],
       [508.79984],
       [548.3346 ],
       [562.4965 ],
       [721.1318 ],
       [539.0704 ],
       [616.2359 ],
       [612.98303],
       [616.8844 ],
       [538.8402 ],
       [502.1644 ],
       [521.9048 ],
       [577.6471 ],
       [439.25104],
       [605.1584 ],
       [421.43616],
       [357.62085],
       [437.2315 ],
       [411.91583],
       [491.5044 ],
       [490.22232],
       [409.225  ],
       [480.92935],
       [404.32858],
       [317.69617],
       [590.1102 ],
       [500.39627],
       [391.0325 ],
       [418.0422 ],
       [562.57874],
       [480.07355],
       [462.11676],
       [535.4551 ],
       [541.979  ],
       [564.13495],
       [503.83795],
       [512.4475 ],
       [394.04172],
       [558.62726],
       [584.2456 ],
       [588.65796],
       [439.98956],
       [558.7038 ],
       [388.42926],
       [477.09677],
       [642.28076],
       [631.6859 ],
       [506.25412],
       [604.2039 ],
       [601.2025 ],
       [575.2619 ],
       [465.93704],
       [668.5115 ],
       [350.70035],
       [490.14548],
       [540.98224],
       [527.5052 ],
       [574.60223],
       [639.7555 ],
       [501.55713],
       [487.27444],
       [503.74207],
       [353.2875 ],
       [483.40503],
       [552.534  ],
       [463.8625 ],
       [596.0378 ],
       [566.46484],
       [460.1783 ],
       [449.7637 ],
       [457.1867 ],
       [532.58167],
       [395.87692],
       [509.4346 ],
       [473.73914],
       [349.4722 ],
       [542.33813],
       [402.81168],
       [617.9594 ],
       [661.62744],
       [419.11615],
       [470.29318],
       [501.60217],
       [464.26462],
       [397.38516],
       [614.6899 ],
       [522.7902 ],
       [636.9181 ],
       [328.30545],
       [443.01993],
       [466.13132],
       [324.22955],
       [355.07132],
       [547.5048 ],
       [508.85648],
       [502.92105],
       [479.79156],
       [512.74524],
       [517.7321 ],
       [364.11255],
       [439.40503],
       [519.1089 ],
       [508.11945],
       [547.7583 ],
       [453.29553],
       [456.90057],
       [580.6463 ],
       [492.56137],
       [512.7922 ],
       [461.716  ]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score # accuracy metric for regression task is r squared

In [ ]:
r2_score(ytest,yp)

0.976023762078309