In [1]:
# if you are using Jupyter notebook execute 1st:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
# Dense: to add layers(hidden, output)
from tensorflow.keras import Sequential
# Sequential: to add layers in sequence, to initialize ann model i.e. initially random weight will be assigned
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df # Exited is a target column. Binary Classification problem
# given the customer details, bank want to predict whether customer will leave the bank or not.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Not important columns
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [5]:
df.shape

(10000, 11)

# Data Transformation

In [6]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [8]:
df.drop(columns = ['Exited']) # no permanent deletion of Exited column

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [9]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype = int)  # dtype = int to make encoded values (0,1) permanent
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

# Model Building

In [10]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [11]:
sc = StandardScaler() # don't perform standardization on target column
x = df.drop(columns=['Exited'])# exclude Exited column
y = df['Exited']

In [12]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [13]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [14]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [15]:
# create instance of Sequential class or initialize the model
model = Sequential()
# Sequential is a class in Keras that allows you to build ANN model layer-by-layer.
# create neurons in input, hidden and output layers and assign random weights to input
# In I/P layer 13 input values will be there as there are 13 independent features

#Add hidden layer, randomly 10 neurons are added
model.add(Dense(units=10,activation='relu'))# as target is binary use relu activation
# Layers are added sequentially using the .add() method.
# Each layer receives input from the previous layer and passes output to the next one.

#Add output layer
model.add(Dense(units=1, activation='sigmoid'))# for binary classification use sigmoid activation in output layer

#Establish the connection between the layers
model.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])
# adadelta is gradient descent algorithm for weight updation which we have selected randomly. We will hypertune it afterwards
# binary_crossentropy: also called log_loss, finds erros, range is 0 to 1

#Fit the data, perform forward and back propagation
model.fit(xtrain,ytrain, epochs=100)
# epochs=100 means that the model will go through the entire xtrain and ytrain dataset 100 times during training.
# epoch: backward and forward propagation will be done for 100 times
# The number of batches per epoch = Total number of samples / Batch size (default is 32)
# 80% training data = 8000 samples. So Batches=8000/32 = 250
# Each batch is processed in sequence during each epoch,
# and after all 250 batches are processed, one epoch is complete.

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4153 - loss: 0.8463
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4113 - loss: 0.8396
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4078 - loss: 0.8493
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4151 - loss: 0.8387
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4158 - loss: 0.8345
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4005 - loss: 0.8504
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4062 - loss: 0.8364
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4178 - loss: 0.8385
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4253 - loss: 0.8261
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4226 - loss: 0.8314
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4262 - loss: 0.8247
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4230 - loss: 0.8312
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4138 - loss: 0.8323
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4290 - loss: 0.8190
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4193 - loss: 0.8289
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4314 - loss: 0.8201
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4287 - loss: 0.8260
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4430 - loss: 0.8134
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4319 - loss: 0.8166
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4313 - loss: 0.8189
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4351 - loss: 0.8104
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4364 - loss: 0.8206
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4385 - loss: 0.8116
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4438 - loss: 0.8039
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4422 - loss: 0.8067
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4490 - loss: 0.8029
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4443 - loss: 0.8035
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4394 - loss: 0.8065
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4368 - loss: 0.8104
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4471 - loss: 0.7989
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4532 - loss: 0.8000
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4523 - loss: 0.7929
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4471 - loss: 0.8025
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4599 - loss: 0.7916
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4563 - loss: 0.7963
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4568 - loss: 0.7963
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4587 - loss: 0.7886
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4619 - loss: 0.7910
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4688 - loss: 0.7839
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4668 - loss: 0.7835
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4609 - loss: 0.7813
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4683 - loss: 0.7809
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4665 - loss: 0.7786
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4650 - loss: 0.7830
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4589 - loss: 0.7835
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4641 - loss: 0.7794
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4714 - loss: 0.7817
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4714 - loss: 0.7731
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4689 - loss: 0.7770
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4703 - loss: 0.7766
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4737 - loss: 0.7730
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4739 - loss: 0.7705
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4770 - loss: 0.7691
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4854 - loss: 0.7660
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4876 - loss: 0.7665
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4789 - loss: 0.7621
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4846 - loss: 0.7631
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4892 - loss: 0.7591
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4808 - loss: 0.7630
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4887 - loss: 0.7643
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4897 - loss: 0.7538
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4969 - loss: 0.7561
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4877 - loss: 0.7584
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4912 - loss: 0.7530
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4928 - loss: 0.7557
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4856 - loss: 0.7591
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4966 - loss: 0.7541
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4933 - loss: 0.7523
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4946 - loss: 0.7555
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5019 - loss: 0.7451
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5049 - loss: 0.7417
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4970 - loss: 0.7483
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5071 - loss: 0.7428
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5111 - loss: 0.7399
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4952 - loss: 0.7485
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5059 - loss: 0.7444
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5042 - loss: 0.7433
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5190 - loss: 0.7354
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5104 - loss: 0.7414
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5140 - loss: 0.7343
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5148 - loss: 0.7315
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5049 - loss: 0.7376
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5191 - loss: 0.7363
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5194 - loss: 0.7313
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5367 - loss: 0.7230
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5191 - loss: 0.7311
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5267 - loss: 0.7269
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5394 - loss: 0.7206
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5396 - loss: 0.7183
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5290 - loss: 0.7235
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5237 - loss: 0.7249
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5397 - loss: 0.7163
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5333 - loss: 0.7171
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5306 - loss: 0.7230
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5209 - loss: 0.7286
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5349 - loss: 0.7214
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5446 - loss: 0.7113
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5370 - loss: 0.7196
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5353 - loss: 0.7179
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5335 - loss: 0.7191

In [16]:
# accuracy is not good and error is also high as hyperparameter tuning is not done
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [17]:
ypred = model.predict(xtest)
ypred # in dataset target column values are 0 or 1, but here output is a continuous number
# because in output layer activation function is sigmoid. It gives you o/p in terms of probability
# In sigmoid if probability is > 0.5 it gives you 1 and if probability < 0 it should give 0

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[0.58954424],
       [0.6683034 ],
       [0.50166833],
       ...,
       [0.4238216 ],
       [0.3591241 ],
       [0.47521642]], dtype=float32)

In [18]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [19]:
print(classification_report(ytest,ypred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [20]:
ypred > 0.5 # not it will give me 1 or 0 OR true or false answers

array([[ True],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [21]:
ypred = ypred > 0.5
ypred

array([[ True],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [22]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [23]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.81      0.57      0.67      1585
           1       0.23      0.49      0.32       415

    accuracy                           0.56      2000
   macro avg       0.52      0.53      0.49      2000
weighted avg       0.69      0.56      0.60      2000

# Hyperparameter Tuning

In [24]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras->keras-tuner) (4.14.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.8 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

# **Tuning the ANN Model**
- Selecting the best optimizer

In [3]:
import keras_tuner as kt

ModuleNotFoundError: No module named 'keras_tuner'

In [26]:
# tuning for optimizer(adam,rmsprop or sgd:stochastic gradient descent) only
def optimizer_selection(hp):
    # hp (HyperParameters) is an object used to define search spaces for the hyperparameters you want to tune.
    # This allows the Keras Tuner to explore different values for the hyperparameters
    # and find the best ones during the search.

    #create instance of sequential class
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop']) #value of optimizer is categorical so use choice()function else use hp.Int()
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [27]:
# similar to GridSearchCV() we will use here RandomSearch()
tuner = kt.RandomSearch(
    optimizer_selection,# model name-here Sequential() class is our model
    objective='val_accuracy', # increase accuracy of test data i.e. validation test accuracy or minimize 'val_loss'
    max_trials=3 # for each optimizer take 3 trials: for sgd-3 trials, for adam-3 trials, for rmsprop-3 trials
    # can select 3 to 10 or 20 for larger problems
)

In [28]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))
# tuner.search() is equivalent to grid.fit()
# When we call tuner.search(), we are not directly calling the hyper() function.
# Instead, Keras Tuner automatically calls hyper()
# and passes the hp object to it during the search.
# We don’t manually pass hp as an argument because Keras Tuner handles it behind the scenes.

# epochs should be same as max_trials so 3 is selected
# validation_data: pass test data

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8134999871253967

Best val_accuracy So Far: 0.8330000042915344
Total elapsed time: 00h 00m 12s

In [29]:
tuner.get_best_hyperparameters()[0].values # as per performance all optimizers are stored in an array
# we want high accuracy optimizer present at index 0 location

{'optimizer': 'rmsprop'}

In [30]:
model = tuner.get_best_models(num_models=1)[0] # get best model: rmsprop
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8294 - loss: 0.4037 - val_accuracy: 0.8370 - val_loss: 0.3960
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8378 - loss: 0.3913 - val_accuracy: 0.8395 - val_loss: 0.3866
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8312 - loss: 0.3921 - val_accuracy: 0.8415 - val_loss: 0.3795
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8505 - loss: 0.3686 - val_accuracy: 0.8465 - val_loss: 0.3738
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8462 - loss: 0.3697 - val_accuracy: 0.8450 - val_loss: 0.3683
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8568 - loss: 0.3511 - val_accuracy: 0.8530 - val_loss: 0.3637
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8539 - loss: 0.3538 - val_accuracy: 0.8510 - val_loss: 0.3604
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8463 - loss: 0.3689 - val_accuracy: 0.8500 - val_loss: 0.3576
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8549 - loss: 0.3612 - val_accuracy: 0.8525 - val_loss: 0.3548
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8543 - loss: 0.3554 - val_accuracy: 0.8535 - val_loss: 0.3534
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8645 - loss: 0.3419 - val_accuracy: 0.8535 - val_loss: 0.3507
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3416 - val_accuracy: 0.8535 - val_loss: 0.3501
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8561 - loss: 0.3518 - val_accuracy: 0.8575 - val_loss: 0.3491
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3412 - val_accuracy: 0.8545 - val_loss: 0.3478
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8564 - loss: 0.3489 - val_accuracy: 0.8575 - val_loss: 0.3475
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8616 - loss: 0.3419 - val_accuracy: 0.8585 - val_loss: 0.3461
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3517 - val_accuracy: 0.8570 - val_loss: 0.3452
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8569 - loss: 0.3442 - val_accuracy: 0.8580 - val_loss: 0.3449
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8660 - loss: 0.3324 - val_accuracy: 0.8545 - val_loss: 0.3440
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8594 - loss: 0.3478 - val_accuracy: 0.8565 - val_loss: 0.3444
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8559 - loss: 0.3517 - val_accuracy: 0.8560 - val_loss: 0.3433
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8576 - loss: 0.3447 - val_accuracy: 0.8590 - val_loss: 0.3440
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8646 - loss: 0.3381 - val_accuracy: 0.8580 - val_loss: 0.3428
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8555 - loss: 0.3491 - val_accuracy: 0.8560 - val_loss: 0.3421
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8530 - loss: 0.3534 - val_accuracy: 0.8605 - val_loss: 0.3416
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8577 - loss: 0.3437 - val_accuracy: 0.8595 - val_loss: 0.3420
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8660 - loss: 0.3420 - val_accuracy: 0.8605 - val_loss: 0.3422
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8575 - loss: 0.3350 - val_accuracy: 0.8595 - val_loss: 0.3417
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8602 - loss: 0.3405 - val_accuracy: 0.8600 - val_loss: 0.3417
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8615 - loss: 0.3437 - val_accuracy: 0.8600 - val_loss: 0.3419
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8572 - loss: 0.3499 - val_accuracy: 0.8585 - val_loss: 0.3411
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8537 - loss: 0.3445 - val_accuracy: 0.8600 - val_loss: 0.3418
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8581 - loss: 0.3491 - val_accuracy: 0.8615 - val_loss: 0.3425
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8596 - loss: 0.3487 - val_accuracy: 0.8600 - val_loss: 0.3396
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8644 - loss: 0.3354 - val_accuracy: 0.8615 - val_loss: 0.3415
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3363 - val_accuracy: 0.8590 - val_loss: 0.3405
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8538 - loss: 0.3545 - val_accuracy: 0.8615 - val_loss: 0.3415
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8561 - loss: 0.3502 - val_accuracy: 0.8615 - val_loss: 0.3393
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8602 - loss: 0.3334 - val_accuracy: 0.8590 - val_loss: 0.3402
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8575 - loss: 0.3390 - val_accuracy: 0.8610 - val_loss: 0.3391
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8623 - loss: 0.3368 - val_accuracy: 0.8570 - val_loss: 0.3392
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8615 - loss: 0.3385 - val_accuracy: 0.8595 - val_loss: 0.3389
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3333 - val_accuracy: 0.8590 - val_loss: 0.3390
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8612 - loss: 0.3367 - val_accuracy: 0.8625 - val_loss: 0.3391
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8564 - loss: 0.3476 - val_accuracy: 0.8580 - val_loss: 0.3377
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8547 - loss: 0.3447 - val_accuracy: 0.8605 - val_loss: 0.3404
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8538 - loss: 0.3478 - val_accuracy: 0.8620 - val_loss: 0.3388
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8559 - loss: 0.3392 - val_accuracy: 0.8620 - val_loss: 0.3377
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8560 - loss: 0.3456 - val_accuracy: 0.8610 - val_loss: 0.3378
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8555 - loss: 0.3496 - val_accuracy: 0.8615 - val_loss: 0.3393
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8482 - loss: 0.3490 - val_accuracy: 0.8630 - val_loss: 0.3383
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8544 - loss: 0.3484 - val_accuracy: 0.8615 - val_loss: 0.3380
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3324 - val_accuracy: 0.8620 - val_loss: 0.3369
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8575 - loss: 0.3387 - val_accuracy: 0.8580 - val_loss: 0.3363
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8576 - loss: 0.3379 - val_accuracy: 0.8595 - val_loss: 0.3373
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8589 - loss: 0.3366 - val_accuracy: 0.8615 - val_loss: 0.3361
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3315 - val_accuracy: 0.8615 - val_loss: 0.3363
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8641 - loss: 0.3332 - val_accuracy: 0.8620 - val_loss: 0.3362
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8681 - loss: 0.3295 - val_accuracy: 0.8600 - val_loss: 0.3372
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8638 - loss: 0.3373 - val_accuracy: 0.8615 - val_loss: 0.3365
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8544 - loss: 0.3461 - val_accuracy: 0.8620 - val_loss: 0.3367
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8600 - loss: 0.3368 - val_accuracy: 0.8610 - val_loss: 0.3349
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8599 - loss: 0.3373 - val_accuracy: 0.8630 - val_loss: 0.3355
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8583 - loss: 0.3408 - val_accuracy: 0.8630 - val_loss: 0.3362
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8556 - loss: 0.3496 - val_accuracy: 0.8635 - val_loss: 0.3352
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8636 - loss: 0.3295 - val_accuracy: 0.8630 - val_loss: 0.3356
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8580 - loss: 0.3368 - val_accuracy: 0.8610 - val_loss: 0.3360
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8603 - loss: 0.3367 - val_accuracy: 0.8615 - val_loss: 0.3350
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3310 - val_accuracy: 0.8635 - val_loss: 0.3353
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8660 - loss: 0.3315 - val_accuracy: 0.8615 - val_loss: 0.3336
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8673 - loss: 0.3300 - val_accuracy: 0.8620 - val_loss: 0.3355
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8608 - loss: 0.3349 - val_accuracy: 0.8615 - val_loss: 0.3346
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8568 - loss: 0.3443 - val_accuracy: 0.8610 - val_loss: 0.3357
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8641 - loss: 0.3281 - val_accuracy: 0.8615 - val_loss: 0.3339
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3334 - val_accuracy: 0.8610 - val_loss: 0.3356
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8541 - loss: 0.3475 - val_accuracy: 0.8620 - val_loss: 0.3349
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8655 - loss: 0.3279 - val_accuracy: 0.8625 - val_loss: 0.3344
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8643 - loss: 0.3308 - val_accuracy: 0.8615 - val_loss: 0.3349
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8645 - loss: 0.3313 - val_accuracy: 0.8630 - val_loss: 0.3347
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8642 - loss: 0.3331 - val_accuracy: 0.8635 - val_loss: 0.3335
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8677 - loss: 0.3344 - val_accuracy: 0.8630 - val_loss: 0.3338
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8582 - loss: 0.3384 - val_accuracy: 0.8620 - val_loss: 0.3360
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8653 - loss: 0.3241 - val_accuracy: 0.8630 - val_loss: 0.3341
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8627 - loss: 0.3293 - val_accuracy: 0.8610 - val_loss: 0.3350
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3306 - val_accuracy: 0.8640 - val_loss: 0.3330
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8727 - loss: 0.3151 - val_accuracy: 0.8635 - val_loss: 0.3344
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3253 - val_accuracy: 0.8620 - val_loss: 0.3339
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8633 - loss: 0.3302 - val_accuracy: 0.8645 - val_loss: 0.3336
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8622 - loss: 0.3270 - val_accuracy: 0.8615 - val_loss: 0.3355
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8599 - loss: 0.3394 - val_accuracy: 0.8630 - val_loss: 0.3349
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8679 - loss: 0.3218 - val_accuracy: 0.8615 - val_loss: 0.3334
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8606 - loss: 0.3334 - val_accuracy: 0.8625 - val_loss: 0.3330
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8657 - loss: 0.3226 - val_accuracy: 0.8605 - val_loss: 0.3348
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8633 - loss: 0.3354 - val_accuracy: 0.8605 - val_loss: 0.3343
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8626 - loss: 0.3310 - val_accuracy: 0.8625 - val_loss: 0.3336
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8528 - loss: 0.3456 - val_accuracy: 0.8625 - val_loss: 0.3330
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8672 - loss: 0.3241 - val_accuracy: 0.8610 - val_loss: 0.3338
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8651 - loss: 0.3374 - val_accuracy: 0.8630 - val_loss: 0.3332
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8524 - loss: 0.3501 - val_accuracy: 0.8615 - val_loss: 0.3330
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8559 - loss: 0.3365 - val_accuracy: 0.8620 - val_loss: 0.3332

In [31]:
# In above output we have only hypertuned optimizer and
# we got generalized model having improved accuracy- previously it was 76%
# now we got training accuracy=86.47% and testing accuracy=86.40%
model.evaluate(xtrain,ytrain) # same as score() function

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8665 - loss: 0.3308

[0.33096081018447876, 0.8634999990463257]

In [32]:
model.evaluate(xtest,ytest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8575 - loss: 0.3383

[0.33323630690574646, 0.8619999885559082]

# Regression

In [8]:
df = pd.read_csv('/content/Price.csv')
df

          price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [9]:
x = df.iloc[:,1:]
y = df['price']

In [10]:
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [11]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [12]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))# hidden layer1
ann.add(Dense(units=20, activation='relu'))# hidden layer2

ann.add(Dense(units=1))# output layer.
#In Regression task no activation function is required in output layer as we don't have to convert price to 0 or 1

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 256630.9062 - val_loss: 262447.7188
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 254459.5781 - val_loss: 261697.6562
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 247372.5312 - val_loss: 260517.6875
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 251385.0938 - val_loss: 258649.3125
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 250179.0156 - val_loss: 255895.5469
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 245108.9531 - val_loss: 252049.4062
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 242336.2500 - val_loss: 246875.7656
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237858.9219 - val_loss: 240216.1562
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 232794.7656 - val_loss: 231784.2344
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 219611.6562 - val_loss: 221559.2969
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 213567.6406 - val_loss: 209518.4375
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 202047.8906 - val_loss: 195460.7656
Epoch 13/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 188113.3594 - val_loss: 179905.2344
Epoch 14/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 170329.6562 - val_loss: 162974.4688
Epoch 15/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 151290.1406 - val_loss: 145038.7969
Epoch 16/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 137366.7344 - val_loss: 126667.1875
Epoch 17/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 119019.0156 - val_loss: 108203.3125
Epoch 18/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 98689.6250 - val_loss: 90626.2188
Epoch 19/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 82048.4844 - val_loss: 74009.0078
Epoch 20/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 67024.3750 - val_loss: 59075.4414
Epoch 21/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 52954.6602 - val_loss: 46226.5039
Epoch 22/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 40643.3828 - val_loss: 35487.9609
Epoch 23/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 31952.8223 - val_loss: 26898.8125
Epoch 24/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23127.2246 - val_loss: 20388.4707
Epoch 25/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18203.5078 - val_loss: 15600.8877
Epoch 26/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13452.5762 - val_loss: 12216.0850
Epoch 27/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10749.3594 - val_loss: 9906.4473
Epoch 28/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8725.7451 - val_loss: 8372.2139
Epoch 29/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7470.0640 - val_loss: 7367.6646
Epoch 30/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6912.1172 - val_loss: 6659.7295
Epoch 31/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6125.5049 - val_loss: 6137.4014
Epoch 32/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6092.3604 - val_loss: 5774.4448
Epoch 33/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5389.7856 - val_loss: 5449.7104
Epoch 34/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5347.4185 - val_loss: 5174.3257
Epoch 35/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5137.0991 - val_loss: 4936.7090
Epoch 36/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4748.8218 - val_loss: 4726.8730
Epoch 37/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4979.6631 - val_loss: 4511.3403
Epoch 38/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4838.8281 - val_loss: 4315.8521
Epoch 39/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3922.0947 - val_loss: 4117.3369
Epoch 40/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3930.2866 - val_loss: 3923.5688
Epoch 41/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3931.0203 - val_loss: 3743.4893
Epoch 42/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3873.2222 - val_loss: 3568.4155
Epoch 43/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3833.2078 - val_loss: 3397.4312
Epoch 44/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3473.1123 - val_loss: 3234.4890
Epoch 45/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 3068.0369 - val_loss: 3079.4243
Epoch 46/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 2566.2415 - val_loss: 2926.8591
Epoch 47/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 3024.3130 - val_loss: 2780.4343
Epoch 48/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2576.1047 - val_loss: 2633.3428
Epoch 49/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 2333.1172 - val_loss: 2505.2495
Epoch 50/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2567.0410 - val_loss: 2368.3186
Epoch 51/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2408.7065 - val_loss: 2245.7539
Epoch 52/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2285.9194 - val_loss: 2129.5081
Epoch 53/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 2349.2974 - val_loss: 2019.2104
Epoch 54/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2097.5151 - val_loss: 1902.6702
Epoch 55/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 1933.9192 - val_loss: 1802.2599
Epoch 56/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1905.0941 - val_loss: 1707.0474
Epoch 57/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 1538.1472 - val_loss: 1613.0676
Epoch 58/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1572.6710 - val_loss: 1529.1289
Epoch 59/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1810.7639 - val_loss: 1443.3772
Epoch 60/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1524.9485 - val_loss: 1363.6869
Epoch 61/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1349.1016 - val_loss: 1292.2532
Epoch 62/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1278.9247 - val_loss: 1221.7742
Epoch 63/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1259.1071 - val_loss: 1154.4445
Epoch 64/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1104.8145 - val_loss: 1091.8221
Epoch 65/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1112.5074 - val_loss: 1032.0247
Epoch 66/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1021.7220 - val_loss: 980.6900
Epoch 67/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 900.9625 - val_loss: 927.2967
Epoch 68/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 983.1692 - val_loss: 875.6110
Epoch 69/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 989.4147 - val_loss: 828.8808
Epoch 70/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 887.0078 - val_loss: 784.8829
Epoch 71/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 658.5178 - val_loss: 746.8156
Epoch 72/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 749.7097 - val_loss: 710.6946
Epoch 73/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 760.4443 - val_loss: 671.7422
Epoch 74/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 718.5439 - val_loss: 637.5919
Epoch 75/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 719.5110 - val_loss: 609.0305
Epoch 76/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 636.0099 - val_loss: 582.7001
Epoch 77/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 672.4111 - val_loss: 552.2502
Epoch 78/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 547.5135 - val_loss: 525.7411
Epoch 79/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 561.7133 - val_loss: 501.1988
Epoch 80/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 524.7964 - val_loss: 480.3994
Epoch 81/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 482.7023 - val_loss: 456.6322
Epoch 82/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 426.3116 - val_loss: 436.7288
Epoch 83/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 440.4541 - val_loss: 416.5090
Epoch 84/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 395.5570 - val_loss: 400.8053
Epoch 85/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 484.0611 - val_loss: 382.5971
Epoch 86/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 383.6524 - val_loss: 366.7321
Epoch 87/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 413.1648 - val_loss: 352.6920
Epoch 88/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 384.6696 - val_loss: 338.2377
Epoch 89/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 329.3482 - val_loss: 325.2050
Epoch 90/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 316.8659 - val_loss: 313.4165
Epoch 91/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 399.4911 - val_loss: 301.6487
Epoch 92/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 310.9093 - val_loss: 291.4109
Epoch 93/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 282.9499 - val_loss: 281.2958
Epoch 94/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 336.5350 - val_loss: 273.1579
Epoch 95/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 294.3046 - val_loss: 263.5128
Epoch 96/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 245.4621 - val_loss: 254.8903
Epoch 97/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 269.0385 - val_loss: 246.7723
Epoch 98/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 192.2914 - val_loss: 238.1295
Epoch 99/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 188.0108 - val_loss: 232.4493
Epoch 100/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 258.8392 - val_loss: 224.5214

In [21]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[480.23456],
       [529.1278 ],
       [499.31482],
       [538.4315 ],
       [646.9514 ],
       [344.4637 ],
       [341.34607],
       [373.39517],
       [710.22876],
       [504.92322],
       [482.75314],
       [511.03958],
       [499.69785],
       [366.22   ],
       [550.458  ],
       [488.94028],
       [577.1356 ],
       [551.3544 ],
       [487.2112 ],
       [504.13077],
       [470.53885],
       [602.8876 ],
       [445.228  ],
       [572.27734],
       [427.68954],
       [524.7731 ],
       [382.01523],
       [497.4301 ],
       [545.9923 ],
       [339.69974],
       [443.78088],
       [640.70215],
       [561.5419 ],
       [539.98206],
       [608.63086],
       [551.37415],
       [406.62567],
       [575.0232 ],
       [558.1842 ],
       [523.50305],
       [425.6635 ],
       [718.65625],
       [527.614  ],
       [535.18896],
       [518.71484],
       [455.59122],
       [528.9337 ],
       [521.6958 ],
       [586.65344],
       [471.43484],
       [379.6173 ],
       [628.4009 ],
       [803.7117 ],
       [530.71155],
       [660.9159 ],
       [541.6311 ],
       [495.3499 ],
       [543.8312 ],
       [549.9935 ],
       [370.2392 ],
       [642.4271 ],
       [473.19925],
       [480.01672],
       [510.9153 ],
       [563.537  ],
       [329.21906],
       [557.0823 ],
       [547.08716],
       [445.06973],
       [594.9768 ],
       [554.6146 ],
       [421.80286],
       [463.27417],
       [671.4492 ],
       [400.76157],
       [548.12573],
       [344.34348],
       [452.547  ],
       [595.8871 ],
       [535.07605],
       [446.24008],
       [444.93817],
       [349.84863],
       [470.05658],
       [391.7399 ],
       [662.3585 ],
       [380.6216 ],
       [555.10913],
       [569.60095],
       [362.22052],
       [408.13068],
       [499.55145],
       [552.3318 ],
       [558.9064 ],
       [727.54626],
       [542.1644 ],
       [614.00586],
       [616.90027],
       [622.37964],
       [540.6459 ],
       [498.3428 ],
       [522.48926],
       [581.3927 ],
       [435.48767],
       [610.1488 ],
       [413.44904],
       [361.51276],
       [437.55466],
       [413.19797],
       [493.18604],
       [485.27426],
       [408.6001 ],
       [480.9103 ],
       [409.1589 ],
       [316.16275],
       [586.9641 ],
       [490.90076],
       [390.11142],
       [411.15167],
       [558.928  ],
       [480.21878],
       [463.49557],
       [539.54004],
       [534.3645 ],
       [567.97363],
       [505.74002],
       [512.9679 ],
       [383.17786],
       [560.00464],
       [585.19727],
       [594.51   ],
       [436.4445 ],
       [563.47766],
       [389.5875 ],
       [469.7681 ],
       [648.588  ],
       [635.20935],
       [509.29404],
       [610.5625 ],
       [596.254  ],
       [572.2018 ],
       [465.05435],
       [663.33716],
       [346.45258],
       [490.85916],
       [539.21155],
       [529.2804 ],
       [578.869  ],
       [637.23816],
       [492.00314],
       [489.9891 ],
       [502.2133 ],
       [349.4876 ],
       [485.4664 ],
       [545.34937],
       [464.973  ],
       [602.17676],
       [570.1207 ],
       [459.39444],
       [451.23752],
       [456.5039 ],
       [531.35034],
       [386.9372 ],
       [512.0685 ],
       [472.32733],
       [344.85336],
       [535.1312 ],
       [393.31107],
       [622.10864],
       [665.9813 ],
       [413.61258],
       [466.86514],
       [495.76578],
       [464.29633],
       [399.18387],
       [610.30786],
       [526.6354 ],
       [641.2992 ],
       [337.76038],
       [442.80997],
       [468.06772],
       [323.26013],
       [367.11337],
       [541.72107],
       [503.1754 ],
       [504.91812],
       [481.28635],
       [503.58878],
       [512.74255],
       [365.66275],
       [436.57632],
       [512.83606],
       [501.53552],
       [550.95105],
       [443.65524],
       [456.39572],
       [586.04224],
       [483.60934],
       [503.58316],
       [460.19293]], dtype=float32)

In [26]:
new_input = np.array([[999.787558,999.766096]])

In [29]:
# The model must receive the input in the same preprocessing/scale as your training data.
# If you scaled xtrain with StandardScaler or MinMaxScaler, you must also scale the new input using the same scaler before predicting.
new_input_scaled = sc.transform([[999.787558,999.766096]])
predicted_price = ann.predict(new_input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

In [30]:
print("Predicted Price:", predicted_price)

Predicted Price: [[471.8128]]

In [ ]:
from sklearn.metrics import r2_score # accuracy metric for regression task is r squared

In [ ]:
r2_score(ytest,yp)

0.976023762078309